name: Build MAUI iOS (Unsigned IPA)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET 9 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # 3. Install necessary MAUI workloads
      - name: Install MAUI workloads
        run: |
          dotnet workload install maui-ios
          dotnet workload install maui-android
          dotnet workload restore

      # 4. Restore NuGet packages for iOS project (only iOS target)
      - name: Restore NuGet packages
        run: |
          dotnet restore EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj --framework net9.0-ios

      # 5. Build iOS project (unsigned IPA)
      - name: Build iOS project
        run: |
          dotnet build EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj \
            -f net9.0-ios -c Release \
            /p:BuildIpa=true

      # 6. Upload IPA artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdinPopfest-ipa
          path: EdinPopfest/EdinPopfest.iOS/bin/Release/net9.0-ios/ios-arm64/*.ipa
