name: Build MAUI iOS (Unsigned IPA)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install all MAUI workloads
        run: |
          dotnet workload install maui-ios
          dotnet workload install maui-android
          dotnet workload install maui-windows
          dotnet workload restore

      - name: Restore NuGet packages for iOS
        run: dotnet restore EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj

      - name: Build iOS project (unsigned IPA)
        run: dotnet build EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj -f net9.0-ios -c Release /p:BuildIpa=true

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdinPopfest-ipa
          path: EdinPopfest/EdinPopfest.iOS/bin/Release/net9.0-ios/ios-arm64/*.ipa
