name: Build MAUI iOS (Unsigned IPA)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET 9 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # 3. Install MAUI iOS workload
      - name: Install MAUI workloads
        run: dotnet workload install maui-ios

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore edinpopfest/EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj

      # 5. Build iOS project (unsigned IPA)
      - name: Build iOS project
        run: dotnet build edinpopfest/EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj -f net9.0-ios -c Release /p:BuildIpa=true

      # 6. Upload IPA artifact (use v4)
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdinPopfest-ipa
          path: edinpopfest/EdinPopfest/EdinPopfest.iOS/bin/Release/net9.0-ios/ios-arm64/*.ipa
