name: Build MAUI App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios-android:
    runs-on: macos-latest
    env:
      DOTNET_ROOT: /Users/runner/.dotnet

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
      # Decode and save the P12
      - name: Decode .p12 from secret
        run: |
          echo "Base64 from secret:"
          echo "${{ secrets.IOS_PROVISION_BASE64 }}" | base64 --decode > ios_profile.mobileprovision
          security cms -D -i ios_profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          printf "%s" "${{ secrets.IOS_KEY }}" | tr -d '\r\n' | base64 --decode > ios_distribution.key
          printf "%s" "${{ secrets.IOS_PEM }}" > ios_distribution.pem
          openssl pkcs12 -export -inkey ios_distribution.key -in ios_distribution.pem -out ios_distribution.p12 -name "iPhone Distribution: Marc Armstrong (XVHZQ55ZBQ)" -passout pass:${{ secrets.IOS_P12_PASSWORD }}

      # 2. Setup .NET 9
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # 3. Install MAUI workloads (needed for iOS/Android builds)
      - name: Install MAUI workloads
        run: |
          dotnet workload install maui-ios
          dotnet workload install maui-android

      # 4. Restore NuGet packages for iOS and Android projects
      - name: Restore NuGet packages (iOS)
        run: dotnet restore EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj

      - name: Restore NuGet packages (Android)
        run: dotnet restore EdinPopfest/EdinPopfest.Droid/EdinPopfest.Droid.csproj

      # Decode and save certificate & provisioning profile
      - name: Set up signing
        run: |
          echo "Set up signing:"
          echo "${{ secrets.IOS_PROVISION_BASE64 }}" | base64 --decode > ios_profile.mobileprovision

      - name: Import certificate into keychain
        run: |
          #security create-keychain -p "" build.keychain
          #security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.IOS_P12_PASSWORD }}" -T /usr/bin/codesign
          #security list-keychains -s ~/Library/Keychains/build.keychain
          #security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          #security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

          openssl pkcs12 -in ios_distribution.p12 -nokeys -passin pass:"$IOS_P12_PASSWORD"

          # Full path to keychain
          KEYCHAIN=/Users/runner/Library/Keychains/build.keychain-db

          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

          # Unlock keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

          security list-keychains -s "$KEYCHAIN" /Users/runner/Library/Keychains/login.keychain-db $(security list-keychains | tr -d '"')

          # Set settings
          security set-keychain-settings -t 3600 -l "$KEYCHAIN"

          # Add to search path
          security list-keychains -s "$KEYCHAIN" $(security list-keychains | tr -d '"')

          # Verify info
          security show-keychain-info "$KEYCHAIN"

          # Import P12
          security import ios_distribution.p12 \
            -k "$KEYCHAIN" \
            -P "$IOS_P12_PASSWORD" \
            -T /usr/bin/codesign

          security find-identity -v -p codesigning /Users/runner/Library/Keychains/build.keychain-db
        env:
          KEYCHAIN_PASSWORD: "buildpass123"
          IOS_P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}

      # 6. Build iOS project (signed IPA)
      - name: Build iOS project
        run: |
          dotnet publish EdinPopfest/EdinPopfest.iOS/EdinPopfest.iOS.csproj \
            -f net9.0-ios -c Release \
            /p:BuildIpa=true \
            /p:MtouchLink=none \
            /p:MtouchUseLlvm=false \
            /p:EnableAssemblyILLinking=false \
            /p:CodesignKey="iPhone Distribution: Marc Armstrong (XVHZQ55ZBQ)" \
            /p:CodesignKeyPassword="${{ secrets.EDINPOPFEST }}" \
            /p:ProvisioningProfile="/Users/runner/Library/MobileDevice/Provisioning Profiles/ios_profile.mobileprovision"
            -v diag

      # 7. Upload IPA artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdinPopfest-ipa
          path: EdinPopfest/EdinPopfest.iOS/bin/Release/net9.0-ios/ios-arm64/*.ipa

      # 5. Build Android project
      - name: Build Android project
        run: dotnet build EdinPopfest/EdinPopfest.Droid/EdinPopfest.Droid.csproj -f net9.0-android35.0 -c Release
